Work around for atomic_write() data race exception issue
It is not unusual that we observed the atomic_write() has data race
in multipul threads and can raise exception to stop build as below:
PermissionError: [WinError 5] Access is denied.

Even the %LOCALAPPDATA% suggestion in below links still cannot
totally fix the exceptions in our CI build system
https://github.com/frerich/clcache/pull/334#issuecomment-452475038
https://github.com/frerich/clcache/issues/342

So, simply retry the atomic_write() several times first and then just
pass through if still fails. The save() work around looks only impact
the statistics data accurate. Since The build expection hang is always
show stopper issue for us with top priority, it's OK for us get harden
stable compiler cache with cost of inaccurate statistics info.